package org.example;

import gg.jte.CodeResolver;
import gg.jte.ContentType;
import gg.jte.TemplateEngine;
import gg.jte.resolve.DirectoryCodeResolver;
import org.glassfish.hk2.utilities.binding.AbstractBinder;

import java.nio.file.Path;

/**
 * HK2 binder that registers the Jte TemplateEngine as a singleton.
 * In development mode templates are loaded from disk for hot-reload;
 * in production mode precompiled classes are used.
 */
public class JteBinder extends AbstractBinder {

    @Override
    protected void configure() {
        bind(createTemplateEngine()).to(TemplateEngine.class);
    }

    private TemplateEngine createTemplateEngine() {
        String env = System.getProperty("app.env", "dev");
        if ("dev".equalsIgnoreCase(env)) {
            // Hot-reload: resolve templates from source directory
            CodeResolver codeResolver = new DirectoryCodeResolver(Path.of("src/main/jte"));
            return TemplateEngine.create(codeResolver, ContentType.Html);
        }
        // Production: use precompiled templates generated by jte-maven-plugin
        return TemplateEngine.createPrecompiled(ContentType.Html);
    }
}
